sudo: required

services:
    - docker

before_install:
    - docker build -t jackyu28/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true jackyu28/docker-react npm run test

#deploy:
#   provider: elasticbeanstalk
#   region: 
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name:
#   bucket_path:"docker-react"
#   on:
#     branch: master